//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Variamos.IacTemplateGenerator.IacLanguage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "variamosiacmodel";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"IacTemplateGenerator";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Variamos";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID IacLanguageDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(IacLanguageCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID IacLanguageExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(IacLanguageCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewIacLanguageExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(IacLanguageCommandSetId), 0x0001);
	
		// Package identifier
		public const string IacLanguagePackageId = "129e39c0-9f0c-4a4d-8617-67ee17a6211b";
		
		// Editor factory identifier
		public const string IacLanguageEditorFactoryId = "4f2140a6-6437-47ea-a5a0-94f059ff9f2d";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string IacLanguageModelExplorerToolWindowId = "87d95db3-b7fb-467f-8fe3-e71005870d08";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Variamos.IacTemplateGenerator.IacLanguage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string IacLanguageCommandSetId = "191a61f0-fa08-4476-95de-ebd07038a722";
	}
}